import { useMemo, useState } from "react";
import {
  Sparkles, AlertOctagon, AlertTriangle, Info, Lightbulb, Loader2, ArrowRight, RefreshCw, ShieldCheck,
} from "lucide-react";
import type { Language, Client, CostStatement, Currency } from "../../../types";
import { useAccountingDataset } from "./useAccountingDataset";
import { buildReceivableRows, buildPayableRows } from "../../../lib/receivablesPayables";
import { computeMonthlyFigures, prevMonthKey, monthKeyOf, reportCurrencies, type MonthlyInput } from "../../../lib/monthlyReport";
import { buildInsights, countByPriority, type Insight, type InsightPriority, type InsightKind } from "../../../lib/accountingInsights";
import { PageHeader, Panel, EmptyState, money, btnGhost, CARD } from "./AccountingUI";

const T = {
  title: { en: "AI Financial Assistant", tr: "Yapay Zekâ Mali Asistanı", ar: "المساعد المالي الذكي" },
  subtitle: { en: "Smart Financial Insights — rule-based, explainable observations from your accounting data. Not predictions.", tr: "Akıllı Mali İçgörüler — muhasebe verilerinizden kural tabanlı, açıklanabilir gözlemler. Tahmin değildir.", ar: "رؤى مالية ذكية — ملاحظات قائمة على قواعد وقابلة للتفسير من بيانات محاسبتك. ليست تنبؤات." },
  banner: { en: "Rule-Based Intelligence", tr: "Kural Tabanlı Zekâ", ar: "ذكاء قائم على القواعد" },
  bannerBody: { en: "Every insight below is generated by a transparent rule over real accounting records — no black-box prediction.", tr: "Aşağıdaki her içgörü, gerçek muhasebe kayıtları üzerinde şeffaf bir kuralla üretilir.", ar: "كل رؤية أدناه مُولّدة بقاعدة شفافة على سجلات محاسبية حقيقية." },
  critical: { en: "Critical", tr: "Kritik", ar: "حرج" },
  high: { en: "High", tr: "Yüksek", ar: "مرتفع" },
  medium: { en: "Medium", tr: "Orta", ar: "متوسط" },
  info: { en: "Informational", tr: "Bilgi", ar: "معلوماتي" },
  all: { en: "All", tr: "Tümü", ar: "الكل" },
  none: { en: "No insights — the accounting data looks healthy.", tr: "İçgörü yok — muhasebe verileri sağlıklı görünüyor.", ar: "لا رؤى — تبدو البيانات المحاسبية سليمة." },
  noneFilter: { en: "No insights at this priority.", tr: "Bu öncelikte içgörü yok.", ar: "لا رؤى بهذه الأولوية." },
  impact: { en: "Impact", tr: "Etki", ar: "الأثر" },
  refresh: { en: "Refresh", tr: "Yenile", ar: "تحديث" },
};
const t = (o: { en: string; tr: string; ar: string }, lang: Language) => o[lang] || o.en;

const PRIO_LABEL: Record<InsightPriority, { en: string; tr: string; ar: string }> = {
  critical: T.critical, high: T.high, medium: T.medium, info: { en: "Info", tr: "Bilgi", ar: "معلومة" },
};
const KIND_LABEL: Record<InsightKind, { en: string; tr: string; ar: string }> = {
  summary: { en: "Executive Summary", tr: "Yönetici Özeti", ar: "ملخص تنفيذي" },
  rule: { en: "Rule-Based Insight", tr: "Kural Tabanlı İçgörü", ar: "رؤية قائمة على قاعدة" },
  trend: { en: "Trend Observation", tr: "Eğilim Gözlemi", ar: "ملاحظة اتجاه" },
  action: { en: "Recommended Action", tr: "Önerilen Eylem", ar: "إجراء موصى به" },
};
const PRIO: Record<InsightPriority, { icon: React.ComponentType<{ className?: string }>; ring: string; chip: string; bar: string }> = {
  critical: { icon: AlertOctagon, ring: "border-red-200", chip: "bg-red-50 text-red-700 ring-red-600/20", bar: "bg-red-500" },
  high: { icon: AlertTriangle, ring: "border-amber-200", chip: "bg-amber-50 text-amber-700 ring-amber-600/20", bar: "bg-amber-500" },
  medium: { icon: Info, ring: "border-blue-200", chip: "bg-blue-50 text-blue-700 ring-blue-600/20", bar: "bg-blue-500" },
  info: { icon: Lightbulb, ring: "border-slate-200", chip: "bg-slate-100 text-slate-600 ring-slate-500/20", bar: "bg-slate-300" },
};

export default function AIFinancialAssistantPage({ lang, clients, costStatements, onNavigate }: {
  lang: Language; clients: Client[]; costStatements: CostStatement[]; onNavigate?: (tab: string, ref?: string) => void;
}) {
  const ds = useAccountingDataset(clients, costStatements);
  const nowIso = new Date().toISOString();
  const [prio, setPrio] = useState<InsightPriority | "all">("all");

  const insights = useMemo(() => {
    const receivables = buildReceivableRows(ds.customers, nowIso);
    const payables = buildPayableRows(ds.vendorBills, nowIso);
    const input: MonthlyInput = { invoices: ds.invoices, customerPayments: ds.customerPayments, vendorPayments: ds.vendorPayments, costStatements };
    const thisMonth = monthKeyOf(nowIso);
    const monthly = reportCurrencies(ds.invoices, costStatements).map((cur: Currency) => ({
      currency: cur,
      current: computeMonthlyFigures(input, cur, thisMonth),
      previous: computeMonthlyFigures(input, cur, prevMonthKey(thisMonth)),
    }));
    return buildInsights({ receivables, payables, costStatements, monthly });
  }, [ds.customers, ds.vendorBills, ds.invoices, ds.customerPayments, ds.vendorPayments, costStatements]); // eslint-disable-line react-hooks/exhaustive-deps

  const counts = useMemo(() => countByPriority(insights), [insights]);
  const shown = useMemo(() => (prio === "all" ? insights : insights.filter((i) => i.priority === prio)), [insights, prio]);

  const chips: { id: InsightPriority | "all"; label: string; n: number; cls: string }[] = [
    { id: "all", label: t(T.all, lang), n: counts.total, cls: "bg-slate-900 text-white border-slate-900" },
    { id: "critical", label: t(T.critical, lang), n: counts.critical, cls: "bg-red-600 text-white border-red-600" },
    { id: "high", label: t(T.high, lang), n: counts.high, cls: "bg-amber-500 text-white border-amber-500" },
    { id: "medium", label: t(T.medium, lang), n: counts.medium, cls: "bg-blue-600 text-white border-blue-600" },
    { id: "info", label: t(T.info, lang), n: counts.info, cls: "bg-slate-500 text-white border-slate-500" },
  ];

  return (
    <div className="space-y-5">
      <PageHeader
        title={t(T.title, lang)}
        subtitle={t(T.subtitle, lang)}
        actions={<button onClick={ds.reload} className={btnGhost}><RefreshCw className="w-4 h-4" /><span className="hidden sm:inline">{t(T.refresh, lang)}</span></button>}
      />

      {/* Honest capability banner */}
      <div className="relative overflow-hidden rounded-xl bg-gradient-to-r from-slate-900 via-slate-900 to-slate-800 p-4 flex items-center gap-3.5 shadow-[0_1px_2px_rgba(15,23,42,0.06)]">
        <div className="absolute -right-6 -top-8 w-36 h-36 rounded-full bg-blue-500/10 blur-2xl pointer-events-none" />
        <span className="w-10 h-10 rounded-xl bg-white/10 ring-1 ring-white/15 text-white flex items-center justify-center shrink-0"><Sparkles className="w-5 h-5" /></span>
        <div className="min-w-0 relative">
          <p className="text-[13px] font-bold text-white flex items-center gap-1.5"><ShieldCheck className="w-4 h-4 text-emerald-400" />{t(T.banner, lang)}</p>
          <p className="text-[11.5px] text-slate-300 mt-0.5 leading-relaxed max-w-2xl">{t(T.bannerBody, lang)}</p>
        </div>
      </div>

      {/* Priority filter chips */}
      <div className="flex flex-wrap items-center gap-2">
        {chips.map((c) => (
          <button key={c.id} onClick={() => setPrio(c.id)} className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[12px] font-semibold cursor-pointer border transition-all ${prio === c.id ? c.cls : "bg-white text-slate-600 border-slate-200 hover:border-slate-300"}`}>
            {c.label}<span className={`tabular-nums ${prio === c.id ? "opacity-90" : "text-slate-400"}`}>{c.n}</span>
          </button>
        ))}
      </div>

      {ds.loading ? (
        <div className="flex items-center justify-center py-16 text-slate-400"><Loader2 className="w-6 h-6 animate-spin" /></div>
      ) : insights.length === 0 ? (
        <EmptyState icon={ShieldCheck} title={t(T.none, lang)} />
      ) : shown.length === 0 ? (
        <EmptyState icon={Lightbulb} title={t(T.noneFilter, lang)} />
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {shown.map((ins) => <InsightCard key={ins.id} lang={lang} ins={ins} onNavigate={onNavigate} />)}
        </div>
      )}
    </div>
  );
}

function InsightCard({ lang, ins, onNavigate }: { lang: Language; ins: Insight; onNavigate?: (tab: string, ref?: string) => void }) {
  const p = PRIO[ins.priority];
  const Icon = p.icon;
  return (
    <div className={`relative overflow-hidden ${CARD} ${p.ring} p-4`}>
      <span className={`absolute inset-y-0 left-0 w-1 ${p.bar}`} />
      <div className="flex items-start gap-3 pl-1.5">
        <span className={`w-9 h-9 rounded-lg flex items-center justify-center shrink-0 ring-1 ring-inset ${p.chip}`}><Icon className="w-[18px] h-[18px]" /></span>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 flex-wrap">
            <span className={`inline-flex items-center px-2 py-0.5 rounded-md text-[9.5px] font-semibold uppercase tracking-wide ring-1 ring-inset ${p.chip}`}>{t(PRIO_LABEL[ins.priority], lang)}</span>
            <span className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{t(KIND_LABEL[ins.kind], lang)}</span>
          </div>
          <p className="mt-1.5 text-[13.5px] font-bold text-slate-900 leading-snug">{ins.title}</p>
          <p className="mt-1 text-[12px] text-slate-500 leading-relaxed">{ins.detail}</p>
          <div className="mt-2.5 flex items-center justify-between gap-3 flex-wrap">
            {ins.impact ? (
              <span className="text-[11.5px] font-semibold text-slate-400">{t(T.impact, lang)}: <span className={`tabular-nums ${ins.impact.amount < 0 ? "text-red-600" : "text-slate-700"}`}>{money(ins.impact.amount)} {ins.impact.currency}</span></span>
            ) : <span />}
            {ins.link && (
              <button onClick={() => onNavigate?.(ins.link!.tab, ins.link!.ref)} className="inline-flex items-center gap-1 text-[11.5px] font-semibold text-blue-600 hover:text-blue-700 cursor-pointer bg-transparent border-0 p-0">
                {ins.link.label}<ArrowRight className="w-3.5 h-3.5" />
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
